/**
 * Creating a sidebar enables you to:
 * - Create an ordered group of docs
 * - Render a sidebar for each doc of that group
 * - Hiden the sidebar from pages that are not docs
 */

// By default, Docusaurus generates a sidebar from the docs folder structure
// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

/**
 * Sidebar for the Physical AI & Humanoid Robotics Textbook.
 * This defines the structure for the 4 main modules and their chapters.
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {type: 'doc', id: 'module1-ros2/chapter1'}, // Placeholder intro page
      items: [
        'module1-ros2/chapter1',
        'module1-ros2/chapter2',
        'module1-ros2/chapter3',
        'module1-ros2/chapter4',
        'module1-ros2/chapter5',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      link: {type: 'doc', id: 'module2-gazebo/chapter1'}, // Placeholder intro page
      items: [
        'module2-gazebo/chapter1',
        'module2-gazebo/chapter2',
        'module2-gazebo/chapter3',
        'module2-gazebo/chapter4',
        'module2-gazebo/chapter5',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      link: {type: 'doc', id: 'module3-isaac/chapter1'}, // Placeholder intro page
      items: [
        'module3-isaac/chapter1',
        'module3-isaac/chapter2',
        'module3-isaac/chapter3',
        'module3-isaac/chapter4',
        'module3-isaac/chapter5',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      link: {type: 'doc', id: 'module4-vla/chapter1'}, // Placeholder intro page
      items: [
        'module4-vla/chapter1',
        'module4-vla/chapter2',
        'module4-vla/chapter3',
        'module4-vla/chapter4',
        'module4-vla/chapter5',
      ],
    },
  ],
};

module.exports = sidebars;