<?xml version="1.0"?>
<robot name="generic_humanoid" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Define common properties/macros -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="body_mass" value="1.0" />
  <xacro:property name="body_len" value="0.2" />
  <xacro:property name="body_rad" value="0.05" />

  <!-- Macro for a generic cylinder link with inertia -->
  <xacro:macro name="cylinder_link" params="name mass length radius">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <material name="blue">
          <color rgba="0 0 0.8 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12)*mass*(3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12)*mass*(3*radius*radius + length*length)}" iyz="0.0"
                 izz="${(1/2)*mass*radius*radius}"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- Base Link: Torso -->
  <xacro:cylinder_link name="torso_link" mass="${body_mass}" length="${body_len}" radius="${body_rad}"/>

  <!-- Head Joint and Link -->
  <joint name="head_joint" type="revolute">
    <parent link="torso_link"/>
    <child link="head_link"/>
    <origin xyz="0 0 ${body_len/2 + body_len/4}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-M_PI/4}" upper="${M_PI/4}" effort="10.0" velocity="1.0"/>
  </joint>
  <xacro:cylinder_link name="head_link" mass="${body_mass/4}" length="${body_len/2}" radius="${body_rad/2}"/>

  <!-- Right Shoulder Joint and Link -->
  <joint name="right_shoulder_joint" type="revolute">
    <parent link="torso_link"/>
    <child link="right_upper_arm_link"/>
    <origin xyz="0 ${-(body_rad + body_len/4)} 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="10.0" velocity="1.0"/>
  </joint>
  <xacro:cylinder_link name="right_upper_arm_link" mass="${body_mass/4}" length="${body_len}" radius="${body_rad/3}"/>

  <!-- Right Elbow Joint and Link -->
  <joint name="right_elbow_joint" type="revolute">
    <parent link="right_upper_arm_link"/>
    <child link="right_forearm_link"/>
    <origin xyz="0 0 ${-body_len/2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="${-M_PI/2}" upper="${0}" effort="10.0" velocity="1.0"/>
  </joint>
  <xacro:cylinder_link name="right_forearm_link" mass="${body_mass/6}" length="${body_len}" radius="${body_rad/4}"/>

</robot>
